# Form implementation generated from reading ui file '.\Auth_Widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow.resize(316, 340)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(316, 340))
        MainWindow.setMaximumSize(QtCore.QSize(316, 340))
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("\n"
"background-size: cover;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(90, 67, 134, 255), stop:1 rgba(255, 255, 255, 255));")
        MainWindow.setWindowFilePath("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.authBtn = QtWidgets.QPushButton(self.centralwidget)
        self.authBtn.setGeometry(QtCore.QRect(10, 250, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.authBtn.setFont(font)
        self.authBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8993c8;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #333333;\n"
"    background-color: #aa55ff;\n"
"}\n"
"")
        self.authBtn.setAutoDefault(False)
        self.authBtn.setObjectName("authBtn")
        self.passwordEnter = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEnter.setGeometry(QtCore.QRect(60, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passwordEnter.setFont(font)
        self.passwordEnter.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.passwordEnter.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordEnter.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.passwordEnter.setObjectName("passwordEnter")
        self.loginEnter = QtWidgets.QLineEdit(self.centralwidget)
        self.loginEnter.setGeometry(QtCore.QRect(60, 140, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.loginEnter.setFont(font)
        self.loginEnter.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.loginEnter.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginEnter.setPlaceholderText("")
        self.loginEnter.setObjectName("loginEnter")
        self.regBtn = QtWidgets.QPushButton(self.centralwidget)
        self.regBtn.setGeometry(QtCore.QRect(170, 250, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.regBtn.setFont(font)
        self.regBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8993c8;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #333333;\n"
"    background-color: #aa55ff;\n"
"}")
        self.regBtn.setObjectName("regBtn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 311, 121))
        self.frame.setAcceptDrops(False)
        self.frame.setStyleSheet("background-color: transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 311, 21))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 301, 71))
        self.label_2.setStyleSheet("background: transparent;")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setLineWidth(0)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\../sources/icons8-автосервис-64.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.authBtn.setText(_translate("MainWindow", "Авторизоваться"))
        self.regBtn.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.label.setText(_translate("MainWindow", "Сеть автосервисов \"Дым и колёса\""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
