# Form implementation generated from reading ui file '.\Main_Widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 554)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(90, 67, 134, 255), stop:1 rgba(255, 255, 255, 255));")
        self.hello_msg = QtWidgets.QLabel(Form)
        self.hello_msg.setGeometry(QtCore.QRect(10, 10, 371, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        self.hello_msg.setFont(font)
        self.hello_msg.setStyleSheet("background-color: transparent;")
        self.hello_msg.setText("")
        self.hello_msg.setObjectName("hello_msg")
        self.leave_btn = QtWidgets.QPushButton(Form)
        self.leave_btn.setGeometry(QtCore.QRect(970, 10, 21, 20))
        self.leave_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../sources/leave-icon12.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leave_btn.setIcon(icon)
        self.leave_btn.setObjectName("leave_btn")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 971, 491))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.pos_msg = QtWidgets.QLabel(Form)
        self.pos_msg.setGeometry(QtCore.QRect(430, 10, 281, 21))
        self.pos_msg.setStyleSheet("background-color: transparent;")
        self.pos_msg.setText("")
        self.pos_msg.setObjectName("pos_msg")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Главный экран"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
