# Form implementation generated from reading ui file '.\Reg_Widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(366, 359)
        Form.setMinimumSize(QtCore.QSize(366, 359))
        Form.setMaximumSize(QtCore.QSize(366, 359))
        Form.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(90, 67, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.regBtn = QtWidgets.QPushButton(Form)
        self.regBtn.setGeometry(QtCore.QRect(110, 290, 141, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regBtn.sizePolicy().hasHeightForWidth())
        self.regBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.regBtn.setFont(font)
        self.regBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.regBtn.setStyleSheet("QPushButton {\n"
"    background-color: #8993c8;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 1px solid #333333;\n"
"    background-color: #aa55ff;\n"
"}\n"
"")
        self.regBtn.setObjectName("regBtn")
        self.first_name = QtWidgets.QLineEdit(Form)
        self.first_name.setGeometry(QtCore.QRect(20, 100, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_name.sizePolicy().hasHeightForWidth())
        self.first_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.first_name.setFont(font)
        self.first_name.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.first_name.setObjectName("first_name")
        self.last_name = QtWidgets.QLineEdit(Form)
        self.last_name.setGeometry(QtCore.QRect(20, 140, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_name.sizePolicy().hasHeightForWidth())
        self.last_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.last_name.setFont(font)
        self.last_name.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.last_name.setObjectName("last_name")
        self.positions = QtWidgets.QComboBox(Form)
        self.positions.setGeometry(QtCore.QRect(100, 250, 161, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positions.sizePolicy().hasHeightForWidth())
        self.positions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.positions.setFont(font)
        self.positions.setStyleSheet("QComboBox {\n"
"    background-color: transparent;\n"
"    border: 2px solid #aa55ff;\n"
"}\n"
"QListView {\n"
"    background-color: rgb(170, 85, 255);\n"
"};")
        self.positions.setObjectName("positions")
        self.login = QtWidgets.QLineEdit(Form)
        self.login.setGeometry(QtCore.QRect(200, 100, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login.setFont(font)
        self.login.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(200, 140, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.email = QtWidgets.QLineEdit(Form)
        self.email.setGeometry(QtCore.QRect(20, 180, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email.sizePolicy().hasHeightForWidth())
        self.email.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.email.setObjectName("email")
        self.phone_number = QtWidgets.QLineEdit(Form)
        self.phone_number.setGeometry(QtCore.QRect(200, 180, 141, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_number.sizePolicy().hasHeightForWidth())
        self.phone_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_number.setFont(font)
        self.phone_number.setStyleSheet("QLineEdit {\n"
"    color: rgb(170, 170, 255);\n"
"    background-color:#34495e;\n"
"    border: 2px solid #aa55ff;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.phone_number.setObjectName("phone_number")
        self.icon = QtWidgets.QLabel(Form)
        self.icon.setGeometry(QtCore.QRect(100, 10, 151, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setStyleSheet("background-color: transparent;")
        self.icon.setText("")
        self.icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.icon.setObjectName("icon")
        self.email_error = QtWidgets.QLabel(Form)
        self.email_error.setGeometry(QtCore.QRect(20, 220, 141, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_error.sizePolicy().hasHeightForWidth())
        self.email_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.email_error.setFont(font)
        self.email_error.setStyleSheet("color: red;\n"
"background-color: transparent;")
        self.email_error.setText("")
        self.email_error.setObjectName("email_error")
        self.phone_number_error = QtWidgets.QLabel(Form)
        self.phone_number_error.setEnabled(True)
        self.phone_number_error.setGeometry(QtCore.QRect(200, 220, 141, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_number_error.sizePolicy().hasHeightForWidth())
        self.phone_number_error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.phone_number_error.setFont(font)
        self.phone_number_error.setStyleSheet("color: red;\n"
"background-color: transparent;")
        self.phone_number_error.setText("")
        self.phone_number_error.setObjectName("phone_number_error")
        self.passwordIsVisible = QtWidgets.QCheckBox(Form)
        self.passwordIsVisible.setGeometry(QtCore.QRect(310, 30, 51, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordIsVisible.sizePolicy().hasHeightForWidth())
        self.passwordIsVisible.setSizePolicy(sizePolicy)
        self.passwordIsVisible.setStyleSheet("background-color: transparent;")
        self.passwordIsVisible.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../sources/show_pass_icon32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.passwordIsVisible.setIcon(icon)
        self.passwordIsVisible.setIconSize(QtCore.QSize(32, 32))
        self.passwordIsVisible.setObjectName("passwordIsVisible")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.regBtn.setText(_translate("Form", "Зарегистрироваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
